version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "Dotnet@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "C:\\Program Files\\Microsoft SQL Server\\MSSQL16.SQLEXPRESS02\\MSSQL\\Backup:/var/opt/mssql/backup"
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc_app_container
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NewDatabase;User Id=SA;Password=Dotnet@123;
    ports:
      - "8080:80"
    networks:
      - mynetwork
